blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/RiversideValley/Flux/discussions
    about: Discuss topics with the community, rather than directly with the developers. Use this for things to share and examples of code, questions about use, or less important issues.
  - name: 📧 Mail
    url: mailto:git@andrexial.org.uk
    about: Email the head of the Flux department at Depth.
